#!/usr/bin/env sh


docker buildx build \
  --platform linux/amd64,linux/arm64,linux/arm/v7 \
  --label org.label-schema.build-date=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
  --label org.label-schema.vcs-ref=$(git rev-parse --short HEAD) \
#  --push \
  --tag carsongee/drone-poetry \
  --tag carsongee/drone-poetry:$(git rev-parse --abbrev-ref HEAD) \
#  --tag carsongee/drone-poetry:v0.1.0 \
#  --tag carsongee/drone-poetry:stable \
  .
